"use client"
import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { Lock, Moon, Sun, Menu, X } from "lucide-react";
import { useState } from "react";
import Link from "next/link";
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isDark, setIsDark] = useState(false);

  // Initialize dark mode from localStorage

  // Handle dark mode toggle
  const toggleDarkMode = () => {
    const html = document.documentElement;
    if (html.classList.contains("dark")) {
      html.classList.remove("dark");
      localStorage.setItem("darkMode", "false");
      setIsDark(false);
    } else {
      html.classList.add("dark");
      localStorage.setItem("darkMode", "true");
      setIsDark(true);
    }
  };
  return (
    <html lang="en">
          <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-sm border-b-2 border-[#693382]">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* Logo / Home Link */}
        <Link
          href="/"
          className="text-[#f0f0f0] text-3xl font-serif font-light font-blanka hover:scale-105 duration-500 tracking-wide hover:text-accent transition-colors"
        >
          LINKCARD
        </Link>


        {/* Dark Mode Toggle & Mobile Menu Button */}
        <div className="flex items-center gap-2">
          <Link
            href="/admin"
            className="p-2 rounded hover:bg-secondary transition-colors"
            title="Admin"
          >
            <Lock className="w-5 h-5 text-white" />
          </Link>
        </div>
      </div>

    </header>
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
